image: ondrejsika/ci

stages:
    - build
    - test
    - deploy

variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG
    COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    # define those variables in Gitlab CI Settings
    # BASE_HOST: host-demo.xsika.cz

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
    stage: build
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-tests.yml
    script:
        - docker-compose build
        - docker-compose push

test:
    stage: test
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-tests.yml
    script:
        - docker-compose pull
        - docker-compose up --no-build tests 
        - docker-compose down


.deploy-template: &deploy-template
    stage: deploy
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
        COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
        DOCKER_HOST: tcp://$BASE_HOST:2376
        HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST

deploy:
    <<: *deploy-template
    script:
        - docker-compose pull
        - docker-compose up -d --no-build
    environment:
        name: $CI_COMMIT_REF_SLUG
        url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST
        on_stop: stop_deploy

stop_deploy:
    <<: *deploy-template
    script:
        - docker-compose down
    when: manual
    environment:
        name: $CI_COMMIT_REF_SLUG
        action: stop