version: '3.7'
services:
    server:
        networks:
            - default
            - traefik
        labels:
            - "traefik.frontend.rule=Host:${HOST:-localhost}"
            - "traefik.enable=true"
networks:
    traefik:
        external:
            name: traefik